Add insecure_skip_tls_verify flag
jgriff/k8s-resource pull request #20
Opened 2021-09-12 14:39 UTC by archanyhm

Added the kubectl `insecure-skip-tls-verify` flag

```yaml
source:
  insecure_skip_tls_verify: true
```

Defaults to false.

2021-09-12 18:20 UTC, jgriff requested changes
Thanks for the PR! Can you update the README to document this new source config option, and its implications for overriding the `certificate_authority ` config if it is also present?  Essentially, now either `certificate_authority` must be configured _or_ `insecure_skip_tls_verify` must be `true`.

2021-09-12 20:03 UTC, archanyhm commented
I updated the README to describe the configuration and it's implications.
I'm not a native English speaker, so I hope the description is OK.

Thanks for providing this repository, by the way!

2021-09-13 15:48 UTC, jgriff approved these changes

2021-09-13 15:53 UTC, merged

2021-09-13 16:03 UTC, jgriff commented
I added test coverage for this new config option, polished the `README` a bit, and squashed/merged.

Version [`0.0.7`](https://github.com/jgriff/k8s-resource/releases/tag/v0.0.7) has been released with this new feature in it.

```
docker pull jgriff/k8s-resource:0.0.7
```

Thanks @archanyhm for the contribution!